### ISSUE TITLE
PCA model does not save (0.9.80)

### ISSUE THREAD

**Issue by mrvejar** [xraypy/xraylarch#522] opened 2024-07-08 23:03 UTC
Under the PCA tab, selcted "Save PCA Model" after building a PCA model. Status bar at the bottom of GUI reads that the .pcamod file was saved, but the actual file is not stored anywhere, i.e. does not save.

**Comment by newville** [comment] 2024-07-09 02:14
@mrvejar Sorry for the trouble.  I will fix this soon.  I am hoping to push out 0.9.79 this week, but keep finding buglets!

**Comment by mrvejar** [comment] 2024-08-14 20:05
I have encountered this issue where the PCA model (.pcamod file) is not saved in Larch version 0.9.80

**Comment by newville** [comment] 2024-08-14 21:05
@mrvejar Oh, I thought we fixed that... I'll take a look (hopefully this week!).

**Comment by newville** [comment] 2024-08-15 03:46
@mrvejar This works for me, in at least one example. Can you give more details or provide a project file?

**Comment by mrvejar** [comment] 2024-08-15 16:49
@newville Thank you so much for checking out the issue. I am attaching a screenshot where the status at the bottom of the Larix GUI says that the PCA model file has been saved, however, the file is not saved/written in the destination folder, or in any of the Larch folders (at least as far as I can tell). I am attaching here .proj file as well. 
![image](https://github.com/user-attachments/assets/0ebce575-fed2-43a5-bd42-64f02037004c)
[Representative XANES spots_trimmed_norm_2024-08-09_1237.zip](https://github.com/user-attachments/files/16627658/Representative.XANES.spots_trimmed_norm_2024-08-09_1237.zip)

**Comment by newville** [comment] 2024-08-16 00:56
@mrvejar Thanks and sorry for the trouble.  I can reproduce this on Windows.  A fix is in progress....

**Comment by mrvejar** [comment] 2024-08-16 00:59
No trouble at all, and many thanks to you @newville !

**Closed** 2024-10-15 19:44 UTC
