### ISSUE TITLE
[Larix/feff fitting] plot each path not working under Windows (Larch 0.9.78)

### ISSUE THREAD

**Issue by nams-549** [xraypy/xraylarch#515] opened 2024-05-24 13:53 UTC
I updated larch and now larix isn't working. How do I resolve?

**Comment by newville** [comment] 2024-05-24 15:35
@nams-549 well, that probably depends on what the problem is. 

What operating system are you using?  What you did to install, update, or try to run the program?   Were there any error messages?

One possibility (though maybe not the best one) would be to delete the installation folder completely and reinstall from the installer.

**Comment by nams-549** [comment] 2024-05-26 19:26
Hii,
Thanks you very much for replying. Sorry for not being clear on the previous message. I'm using windows 11.  I faced the issue once I updated larch to the newer version. Then I deleted and reinstalled the software. 

Now it works fine except the "_plot each path_ " command in the _feff fitting tab_.  The command doesn't seem to work .This feature was very helpful to track the contribution of each path and now I'm unable to use it. 

![image](https://github.com/xraypy/xraylarch/assets/167364078/6f1868b2-ae5c-455f-966f-2f93019d67e0)
![image](https://github.com/xraypy/xraylarch/assets/167364078/a1cf89fe-5737-456a-831f-4b765f98efc3)

**Comment by newville** [comment] 2024-05-28 18:38
@maurov @nams-549 Yes, this is fixed in the master branch.  A warning about that though: I have been playing with the ability to plot a sum of paths (and individual paths) without data.  I believe this is now working, but I changed a lot of code in this area (in feffit_panel.py).  I have tested it on some real examples but feel like I should probably test it more before all of that is released again.

**Comment by tuheihei** [comment] 2024-06-09 08:55
> @maurov @nams-549 Yes, this is fixed in the master branch. A warning about that though: I have been playing with the ability to plot a sum of paths (and individual paths) without data. I believe this is now working, but I changed a lot of code in this area (in feffit_panel.py). I have tested it on some real examples but feel like I should probably test it more before all of that is released again.

Hi, Newville, may I ask how to get this bug fixed? I installed Larch from conda-forge. Should I just wait for another release? Thanks

**Comment by newville** [comment] 2024-06-09 11:48
You can do a pip install of the nightly builds, as described in the documentation.

**Comment by josephzsombor** [comment] 2024-06-13 18:38
I'm having this issue in Linux too. Just installed the most recent version.

**Comment by newville** [comment] 2024-06-13 19:32
@josephzsombor Yeah, sorry.   This is fixed in the nightly build.  See https://xraypy.github.io/xraylarch/installation.html#installing-the-development-version

**Closed** 2024-07-18 14:26 UTC
