### ISSUE TITLE
import error on install

### ISSUE THREAD

**Issue by jordanpoitras** [xraypy/xraylarch#332] opened 2021-12-08 00:38 UTC
I'm having trouble re-installing larch

I'm using a MacBook (Catalina 10.15.7) and was using Larch with no issue. the book was repaired and apple replaced the logic board. This has caused a lot of other headache for my non-apple softwares so I know it's not really an issue on larch's end but something else that needs to be reconfigured. I hope some one can help point me in the right direction. 

When I first tried to launch GSE map viewer the application started and quit

I removed larch and reinstalled using the script. had the same issue but this time the desktop icons failed to be created. I then removed larch as well as python from the system. then reinstalled larch using the script. This is the error that comes up in the install and when launching gse_mapviewer respectively.

## Creating desktop shortcuts
Traceback (most recent call last):
  File "/Users/admin/xraylarch/bin/larch", line 5, in <module>
    from larch.apps import run_larch
  File "/Users/admin/xraylarch/lib/python3.9/site-packages/larch/__init__.py", line 52, in <module>
    from . import builtins
  File "/Users/admin/xraylarch/lib/python3.9/site-packages/larch/builtins.py", line 22, in <module>
    from . import io
  File "/Users/admin/xraylarch/lib/python3.9/site-packages/larch/io/__init__.py", line 39, in <module>
    from .specfile_reader import (str2rng_larch, read_specfile, open_specfile,
  File "/Users/admin/xraylarch/lib/python3.9/site-packages/larch/io/specfile_reader.py", line 26, in <module>
    from silx.io.convert import write_to_h5, _is_commonh5_group
ImportError: cannot import name '_is_commonh5_group' from 'silx.io.convert' (/Users/admin/xraylarch/lib/python3.9/site-packages/silx/io/convert.py)

and same issue when launching 

admin@Jordans-MBP ~ % /Users/admin/xraylarch/bin/gse_mapviewer ; exit;
Traceback (most recent call last):
  File "/Users/admin/xraylarch/bin/gse_mapviewer", line 5, in <module>
    from larch.apps import run_gse_mapviewer
  File "/Users/admin/xraylarch/lib/python3.9/site-packages/larch/__init__.py", line 52, in <module>
    from . import builtins
  File "/Users/admin/xraylarch/lib/python3.9/site-packages/larch/builtins.py", line 22, in <module>
    from . import io
  File "/Users/admin/xraylarch/lib/python3.9/site-packages/larch/io/__init__.py", line 39, in <module>
    from .specfile_reader import (str2rng_larch, read_specfile, open_specfile,
  File "/Users/admin/xraylarch/lib/python3.9/site-packages/larch/io/specfile_reader.py", line 26, in <module>
    from silx.io.convert import write_to_h5, _is_commonh5_group
ImportError: cannot import name '_is_commonh5_group' from 'silx.io.convert' (/Users/admin/xraylarch/lib/python3.9/site-packages/silx/io/convert.py)

**Comment by newville** [comment] 2021-12-08 02:17
@jordanpoitras @maurov Sorry for the trouble, but now I see this too when upgrading to silx 1.0.  It looks like silx 1.0.0 removed this.   I find their code a little challenging to navigate, but I think that in 0.15.2, it was

```
def _is_commonh5_group(grp):
    """Return True if grp is a commonh5 group.
    (h5py.Group objects are not commonh5 groups)"""
    return is_group(grp) and not isinstance(grp, h5py.Group)
```

with `is_group` was defined as 

```
def is_group(obj):
    """
    True if the object is a h5py.Group-like object. A file is a group.
    :param obj: An object
    """
    t = get_h5_class(obj)
    return t in [H5Type.GROUP, H5Type.FILE]
```

(with kind of a lot of convolutions).  I think that means that `_is_commonh5_group(grp)` is just `isinstance(grp, h5py.File)`.
 @maurov does that look right to you?  I think I never tried writing an HDF5 specfile here...

**Comment by maurov** [comment] 2021-12-08 11:36
@jordanpoitras sorry for the trouble, as @newville said, this is coming from upgrading to `silx=1.0.0` and my mistake for importing a private function. Please, simply downgrade to `silx=0.15.2` in the meantime to quickly fix your issue.

@newville I would like to keep using silx utilities to write to HDF5 files. You can simply remove the `_is_commonh5_group` import and the relative line in `specfile_reader.py`. Otherwise, we can stick to `silx=0.15.2` in the requirements for the moment. In view of saving the project file to HDF5, I was planning to rework on this part soon. Are you willing to update the current release to fix this?

**Comment by maurov** [comment] 2021-12-08 12:00
@newville I have looked into the silx code and this check is not required anymore, because now silx can write to HDF5 also if the initial file is HDF5-like.

I took it out your change, as it was not the expected behavior and committed directly to master (https://github.com/xraypy/xraylarch/commit/b76f2ce29b6d183f69a7586ea8daccbe0a89ace3)

**Comment by jordanpoitras** [comment] 2021-12-10 05:08
Thanks for the advice @maurov
I have downgraded silx. However the desktop icons were not created and so I'm not sure how to access the applications. 

when I launch get_mapviewer I get this 

```
admin@Jordans-MBP ~ % /Users/admin/xraylarch/bin/gse_mapviewer ; exit;
This program needs access to the screen. Please run with a
Framework build of python, and only when you are logged in
on the main display of your Mac.

[Process completed]
```

my uneducated guess is that I should launch the portion of the instal script where the desktop icons and all that follows is created so that I can access the application normally using the gui 


Thanks again for the support,
Jordan

**Comment by maurov** [comment] 2021-12-10 08:36
@jordanpoitras my advice is to reinstall Larch using the [GetLarch.sh](https://github.com/xraypy/xraylarch/blob/master/installers/GetLarch.sh) script and install the source version with the option `--devel`, that is:

```bash
GetLarch.sh --devel
```

**Comment by newville** [comment] 2021-12-10 13:20
@jordanpoitras  You should be able to do `larch -m` to fix that.   If that does not work, `
`/Users/admin/xraylarch/bin/python /Users/admin/xraylarch/bin/larch -m`

If that still gives errors, then maybe `conda install python.app`, and then one of those.

That is `larch -m` should create the folder of desktop apps / icons, *and* fix the irritating anaconda-on-MacOS need for "python.app" to run GUI code.

**Comment by maurov** [comment] 2021-12-14 12:30
@jordanpoitras have you solved this issue? Any news?

**Comment by maurov** [comment] 2021-12-14 13:40
OK, great! I will close the issue then.

**Closed by maurov** 2021-12-14 13:40 UTC
Labels: bug
